spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/tiendaspring?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=GMT&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver 
# Configuaraci\u00f3n Creacion de tablas (Hibernate)
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect      
  thymeleaf:
    cache: false 
# Configuraci\u00f3n para cambiar la pagina de error 
server:
  error:
    whitelabel:
      enabled: false


